omz_dir: "{{ ansible_env.HOME }}/.oh-my-zsh"
cargo_home: "{{ ansible_env.HOME }}/.cargo"
cargo_bin: "{{ cargo_home }}/bin"
cargo_path: "{{ cargo_bin }}/cargo"

nerd_fonts_ver: "v3.4.0"
nerd_font: "JetBrainsMono"
font_dir: "{{ ansible_env.HOME }}/.local/share/fonts"
font_zip_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_ver }}/{{ nerd_font }}.zip"
font_zip_path: "/tmp/{{ nerd_font }}-{{ nerd_fonts_ver }}.zip"
font_sentinel: "{{ font_dir }}/.{{ nerd_font }}-{{ nerd_fonts_ver }}.installed"
