alias shortcut='cd $HOME && subl .bash_aliases'
alias salias='cd $HOME source .bash_aliases'

alias gits='git status'
alias gita='git add'
alias gitaa='git add .'
alias gitc='git commit'
alias gitd='git diff'
alias gitds='git diff --staged'
alias gitm='git merge'
alias gitpl='git pull'
alias gitpu='git push'
alias gitrmu='git remote update --prune'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
